services:
  httpd:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "42060:80"
    networks:
      - Annuaire.net

  web:
    image: canals/php:latest
    ports:
      - "42063:80"
    volumes:
      - ./WebDirectoy.core/app:/var/www/html
    working_dir: /var/www/html
    networks:
      - Annuaire.net
    depends_on:
      - sql

  sql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "42061:3307"
    networks:
      - Annuaire.net

  adminer:
    image: adminer
    ports:
      - "42062:8080"
    networks:
      - Annuaire.net  # Corrigé le nom du réseau ici
networks:
  Annuaire.net:
    driver: bridge
